// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/make_code.tsx";
import * as $5 from "./routes/register/[id].tsx";
import * as $6 from "./routes/register/index.tsx";
import * as $7 from "./routes/register_reader/[id].tsx";
import * as $8 from "./routes/register_reader/index.tsx";
import * as $9 from "./routes/sample/index.tsx";
import * as $10 from "./routes/sample/register/[id].tsx";
import * as $11 from "./routes/sample/register/index.tsx";
import * as $12 from "./routes/sample/register_reader/[tmp].tsx";
import * as $13 from "./routes/sample/socket.tsx";
import * as $$0 from "./islands/AddScanItem.tsx";
import * as $$1 from "./islands/CameraButton.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/Reader.tsx";
import * as $$4 from "./islands/RegisterSound.tsx";
import * as $$5 from "./islands/SocketClient.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/make_code.tsx": $4,
    "./routes/register/[id].tsx": $5,
    "./routes/register/index.tsx": $6,
    "./routes/register_reader/[id].tsx": $7,
    "./routes/register_reader/index.tsx": $8,
    "./routes/sample/index.tsx": $9,
    "./routes/sample/register/[id].tsx": $10,
    "./routes/sample/register/index.tsx": $11,
    "./routes/sample/register_reader/[tmp].tsx": $12,
    "./routes/sample/socket.tsx": $13,
  },
  islands: {
    "./islands/AddScanItem.tsx": $$0,
    "./islands/CameraButton.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/Reader.tsx": $$3,
    "./islands/RegisterSound.tsx": $$4,
    "./islands/SocketClient.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
